# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3f49079f-ac0f-4f5a-ba3f-abeec6e1baa0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3f49079f-ac0f-4f5a-ba3f-abeec6e1baa0".device = "/dev/disk/by-uuid/3f49079f-ac0f-4f5a-ba3f-abeec6e1baa0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0ED3-3296";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
